name: Hourly Feature Pipeline

on:
  schedule:
    - cron: "0 * * * *"  # Runs hourly
  workflow_dispatch:  # Allows manual triggering

jobs:
  feature_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch Data
        run: python fetch_data.py

      - name: Compute Features
        run: python compute_features.py

      - name: Update Feature Store
        run: python feature_store.py
